/** Usernames that must not resolve as public Smart Link pages. */
export const SMART_LINK_RESERVED_SLUGS = new Set([
  'admin',
  'api',
  'app',
  'auth',
  'dashboard',
  'login',
  'signup',
  'settings',
  'help',
  'support',
  'about',
  'terms',
  'privacy',
  'pricing',
  'blog',
  'docs',
  'static',
  'assets',
  'images',
  'css',
  'js',
  'fonts',
  'favicon',
  'robots',
  'sitemap',
  'manifest',
  'sw',
  'service-worker',
  'null',
  'undefined',
  'true',
  'false',
  'font-preview',
  'preview',
  'composer',
  'calendar',
  'posts',
  'accounts',
  'connect',
  'reel-analyzer',
  'data-deletion',
]);

export function isSmartLinkReservedSlug(slug: string): boolean {
  return SMART_LINK_RESERVED_SLUGS.has(slug.toLowerCase().trim());
}
