/**
 * 98 niche search phrases for Viral Trend Radar (YouTube search q=).
 * Clusters: wealth, mystery, AI, science, lifestyle, health, food, tech.
 */
export const NICHE_KEYWORDS: string[] = [
  'Rare animals AI',
  'Extinct animals AI',
  'Bizarre nature facts',
  'Deep sea creatures AI',
  'Prehistoric monsters',
  'Animal hybrids',
  'Passive income AI 2026',
  'Side hustle case study',
  'YouTube Automation',
  'Affiliate marketing 2026',
  'Unsolved mysteries',
  'True crime stories',
  'Reddit horror stories',
  'SCARY AI stories',
  'Sora AI news',
  'Kling AI vs Runway',
  'ChatGPT secrets',
  'Stoicism for 2026',
  'Dopamine detox',
  'Biohacking focus',
  'Mars colony update',
  'Quantum computing simplified',
  'Future of work 2026',
  'Digital Nomad life Spain',
  'Moving abroad 2026',
  'Minimalist lifestyle hacks',
  'Ancient civilizations mystery',
  'Lost empires history',
  'Midjourney prompt tips',
  'SaaS founder journey',
  'Crypto macro 2026',
  'Index fund vs stock picking',
  'Real estate investing beginners',
  'Etsy print on demand 2026',
  'Amazon FBA update 2026',
  'Drop shipping honest review',
  'Day trading psychology',
  'Credit score hacks 2026',
  'Van life budget Europe',
  'Japan travel hidden gems',
  'Korean skincare routine science',
  'Meal prep high protein',
  'Gut health microbiome',
  'Zone 2 cardio benefits',
  'Cold plunge research',
  'Longevity diet 2026',
  'Carnivore vs vegan debate',
  'Home gym setup budget',
  'Pickleball strategy tips',
  'Electric vehicle road trip',
  'Smart home automation DIY',
  'Cybersecurity news 2026',
  'Open source AI models',
  'Apple Vision Pro apps',
  'SpaceX Starship update',
  'James Webb discoveries',
  'Fusion energy breakthrough',
  'CRISPR news 2026',
  'Electric plane startup',
  'Underwater archaeology',
  'Pyramid construction theories',
  'Viking history documentary',
  'Roman empire daily life',
  'AI voice clone ethics',
  'Deepfake detection tools',
  'NVIDIA AI chip news',
  'Robotaxi update 2026',
  'Drone delivery cities',
  '3D printed homes',
  'Vertical farming startup',
  'Lab grown meat taste test',
  'Fermentation recipes beginner',
  'Sourdough science tips',
  'Espresso at home budget',
  'Wine tasting for beginners',
  'Whisky investing 2026',
  'Thrift flip furniture',
  'Capsule wardrobe men',
  'Slow fashion brands 2026',
  'Indoor plants low light',
  'Urban gardening balcony',
  'Overlanding Africa route',
  'Camper van electrical setup',
  'Scuba diving best spots',
  'Skiing Japan powder',
  'Marathon training week',
  'Rock climbing finger strength',
  'Tennis serve technique slow',
  'Golf swing fix amateur',
  'Chess opening traps 2026',
  'Speedcubing world record',
  'LEGO investing sealed',
  'Vintage watch collecting',
  'Mechanical keyboard build',
  'PC building mistakes 2026',
  'Steam Deck emulation guide',
  'Indie game dev journey',
  'Blender tutorial beginner 2026',
];
